export const labels: Record<string, any> = {
	id: "ID",
	title: "Judul",
	gallery: "Galeri",
	videoTourUrl: "URL Tur Video",
	excerpt: "Kutipan",
	publishDate: "Tanggal Publikasi",
	deletedAt: "Dihapus Pada",
	archiveReason: "Alasan Arsip",
	make: "Merek",
	model: "Model",
	price: "Harga",
	year: "Tahun",
	mileage: "Jarak Tempuh",
	bodyType: "Tipe Body",
	fuelType: "Bahan Bakar",
	transmission: "Transmisi",
	color: "Warna",
	horsePower: "Tenaga",
	engineSizeCC: "Kapasitas Mesin",
	ownershipStatus: "Status Kepemilikan",
	plateNumber: "Nomor Polisi / Plat Nomor",
	taxExpirationDate: "Masa Berlaku Pajak",
	isFloodFree: "Bukan Bekas Banjir",
	isAccidentFree: "Bebas Lakalantas",
	hasFloodDamage: "Riwayat Terendam Banjir",
	hasAccidentDamage: "Riwayat Tabrakan / Laka",
	seatingCapacity: "Kapasitas Penumpang",
};
